databases:
  - name: bsmai-postgres
    databaseName: bsmai
    user: bsmai
    plan: free

envVarGroups:
- name: bsmai-secrets
  envVars:
    - key: RAILS_MASTER_KEY
      generateValue: true
    - key: SECRET_KEY_BASE
      generateValue: true
    - key: CONFIGURE_ACTIVE_RECORD_ENCRYPTION_FROM_ENV
      value: true
    - key: ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
      generateValue: true
    - key: ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
      generateValue: true
    - key: ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
      generateValue: true

services:
  - type: web
    name: bsmai
    runtime: docker
    plan: free
    healthCheckPath: /up
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bsmai-postgres
          property: connectionString
      - fromGroup: bsmai-secrets
      - key: RUN_SOLID_QUEUE_IN_PUMA
        value: true
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
